# Generated by Django 5.1.5 on 2025-04-06 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Entity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('END', 'Endoscopio flexible'), ('VPR', 'Procesador de video'), ('LIS', 'Fuente de luz'), ('PMP', 'Bomba de irrigación'), ('INF', 'Insuflador de CO²'), ('MON', 'Monitor de grado médico'), ('WST', 'Estación de trabajo'), ('TEL', 'Telescopio'), ('ECG', 'Unidad de electrocirugía'), ('UDI', 'Sistema de documentación')], max_length=100, verbose_name='Tipo')),
                ('device_gen', models.CharField(choices=[('OPT', 'Optera (170)'), ('EX3', 'Exera III (190)'), ('EX2', 'Exera II (180)'), ('EX1', 'Exera I (160)'), ('LUC', 'Evis Lucera (270)'), ('LUE', 'Evis Lucera Elite (290)'), ('EV3', 'Evis Exera III (190)'), ('EV2', 'Evis Exera II (180)'), ('VSR', 'Visera (150/160)'), ('VSP', 'Visera Pro'), ('VSE', 'Visera Elite'), ('VS2', 'Visera Elite II'), ('X1P', 'X1 Series'), ('OIP', 'Procesador de imágenes'), ('CV1', 'Serie CV-100'), ('CV2', 'Serie CV-200'), ('CV3', 'Serie CV-300'), ('CV4', 'Serie CV-400'), ('OES', 'Serie OES'), ('PRO', 'Serie PRO'), ('ULT', 'Serie ULTRA'), ('FIB', 'Fibroscopio de fibra óptica')], max_length=100, verbose_name='Generacion')),
                ('part_number', models.CharField(max_length=100, verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Serie')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Entity.entity', verbose_name='Entidad')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Entity.contract', verbose_name='Contrato')),
                ('device_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model', to='Device.devicemodel', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
    ]
