# Generated by Django 5.1.5 on 2025-05-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='device_gen',
            field=models.CharField(choices=[('OPT', 'Optera (170)'), ('EX3', 'Exera III (190)'), ('EX2', 'Exera II (180)'), ('EX1', 'Exera I (160)'), ('LUC', 'Evis Lucera (270)'), ('LUE', 'Evis Lucera Elite (290)'), ('EV3', 'Evis Exera III (190)'), ('EV2', 'Evis Exera II (180)'), ('VSR', 'Visera (150/160)'), ('VSP', 'Visera Pro'), ('VSE', 'Visera Elite'), ('VS2', 'Visera Elite II'), ('X1P', 'X1 Series'), ('OIP', 'Procesador de imágenes'), ('CV1', 'Serie CV-100'), ('CV2', 'Serie CV-200'), ('CV3', 'Serie CV-300'), ('CV4', 'Serie CV-400'), ('OES', 'Serie OES'), ('PRO', 'Serie PRO'), ('ULT', 'Serie ULTRA'), ('FIB', 'Fibroscopio de fibra óptica'), ('NOG', 'Sin generacion')], max_length=100, verbose_name='Generacion'),
        ),
    ]
