# Generated by Django 5.1.5 on 2025-05-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
