END = [
  [
    {
      "id": "01",
      "name": "Funcionamiento ID",
      "field": "picker",
      "value": "",
    },
    {
      "id": "02",
      "name": "Sin data",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "03",
      "name": "Data errónea",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "04",
      "name": "Sin trasmisión de ID",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "901",
      "name": "",
      "field": "fill",
      "value": "",
    },
    {
      "id": "05",
      "name": "Usos",
      "field": "number",
      "value": "",
    },
    {
      "id": "06",
      "name": "Minutos",
      "field": "number",
      "value": "",
    },
    {
      "id": "07",
      "name": "Comentarios",
      "field": "area",
      "value": "",
    },
  ],
  [
    {
      "id": "11",
      "name": "Imágen  EVIS",
      "field": "picker",
      "value": "",
    },
    {
      "id": "12",
      "name": "Ruido",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "13",
      "name": "Sin imagen con angulación",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "14",
      "name": "Nublado",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "15",
      "name": "Resolución",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "16",
      "name": "Iluminación",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "17",
      "name": "Fantasma",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "18",
      "name": "Imagen girada",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "19",
      "name": "Posición de Pinzas de Biopsia",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "110",
      "name": "Puntos Blancos o Negros",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "111",
      "name": "Función NBI",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "112",
      "name": "Comentarios",
      "field": "area",
      "value": "",
    },
  ],
  [
    {
      "id": "21",
      "name": "Imágen  OES",
      "field": "picker",
      "value": "",
    },
    {
      "id": "22",
      "name": "FI Rotas",
      "field": "number",
      "value": "",
    },
    {
      "id": "23",
      "name": "Humedad",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "24",
      "name": "Tortuga",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "25",
      "name": "Suciedad",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "26",
      "name": "Comentarios",
      "field": "area",
      "value": "",
    },
  ],
  [
    {
      "id": "31",
      "name": "Contacto ocular OES",
      "field": "picker",
      "value": "",
    },
    {
      "id": "32",
      "name": "Con fuga",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "33",
      "name": "Corroido",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "34",
      "name": "Sucio",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "35",
      "name": "Comentarios",
      "field": "area",
      "value": "",
    },
  ],
  [
    {
      "id": "41",
      "name": "Ocular",
      "field": "picker",
      "value": "",
    },
    {
      "id": "42",
      "name": "Nublado",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "43",
      "name": "Corroido",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "44",
      "name": "Comentarios",
      "field": "area",
      "value": "",
    },
  ],
  [
    {
      "id": "51",
      "name": "Imágen  US",
      "field": "picker",
      "value": "",
    },
    {
      "id": "52",
      "name": "Sin imágen",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "53",
      "name": "Con interferencia",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "54",
      "name": "Comentarios",
      "field": "area",
      "value": "",
    },
  ],
  [
    {
      "id": "61",
      "name": "Funcionamiento Botones",
      "field": "picker",
      "value": "",
    },
    {
      "id": "62",
      "name": "SW1",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "63",
      "name": "SW2",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "64",
      "name": "SW3",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "65",
      "name": "SW4",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "66",
      "name": "SW5",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "67",
      "name": "Comentarios",
      "field": "area",
      "value": "",
    },
  ],
  [
    {
      "id": "71",
      "name": "Prueba de hermeticidad",
      "field": "picker",
      "value": "",
    },
    {
      "id": "72",
      "name": "Ubicación fuga",
      "field": "text",
      "value": "",
    },
    {
      "id": "73",
      "name": "Comentarios",
      "field": "area",
      "value": "",
    },
  ],
  [
    {
      "id": "81",
      "name": "Canal de biopsia",
      "field": "picker",
      "value": "",
    },
    {
      "id": "82",
      "name": "Posición de la obstrucción",
      "field": "text",
      "value": "",
    },
    {
      "id": "83",
      "name": "Comentarios",
      "field": "area",
      "value": "",
    },
  ],
  [
    {
      "id": "91",
      "name": "Canal de succión",
      "field": "picker",
      "value": "",
    },
    {
      "id": "92",
      "name": "Posición de la obstrucción",
      "field": "text",
      "value": "",
    },
    {
      "id": "93",
      "name": "Comentarios",
      "field": "area",
      "value": "",
    },
  ],
  [
    {
      "id": "101",
      "name": "Canal Aire/Agua",
      "field": "picker",
      "value": "",
    },
    {
      "id": "102",
      "name": "Contacto con lente",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "103",
      "name": "Eliminación de agua",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "104",
      "name": "Obstruido",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "105",
      "name": "Lento",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "106",
      "name": "Comentarios",
      "field": "area",
      "value": "",
    },
  ],
  [
    {
      "id": "111",
      "name": "Capacidad de insuflación",
      "field": "picker",
      "value": "",
    },
    {
      "id": "112",
      "name": "Obstruido",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "113",
      "name": "Lento",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "114",
      "name": "Comentarios",
      "field": "area",
      "value": "",
    },
  ],
  [
    {
      "id": "121",
      "name": "Canal Auxiliar",
      "field": "picker",
      "value": "",
    },
    {
      "id": "122",
      "name": "Agua auxiliar sale hacia adelante",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "123",
      "name": "Comentarios",
      "field": "area",
      "value": "",
    },
  ],
  [
    {
      "id": "131",
      "name": "Capacidad de succión",
      "field": "picker",
      "value": "",
    },
    {
      "id": "132",
      "name": "Obstruido",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "133",
      "name": "Lento",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "134",
      "name": "Comentarios",
      "field": "area",
      "value": "",
    },
  ],
  [
    {
      "id": "141",
      "name": "Flujo de Canal Elevador",
      "field": "picker",
      "value": "",
    },
    {
      "id": "142",
      "name": "Tubo obstruido",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "143",
      "name": "Comentarios",
      "field": "area",
      "value": "",
    },
  ],
  [
    {
      "id": "151",
      "name": "Irrigador Distal",
      "field": "picker",
      "value": "",
    },
    {
      "id": "152",
      "name": "Saliente",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "153",
      "name": "Abollado",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "154",
      "name": "Deformado",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "155",
      "name": "Obstruido",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "156",
      "name": "Comentarios",
      "field": "area",
      "value": "",
    },
  ],
  [
    {
      "id": "161",
      "name": "Lente de Objetivo",
      "field": "picker",
      "value": "",
    },
    {
      "id": "162",
      "name": "Quebrado",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "163",
      "name": "Astillado",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "164",
      "name": "Rayado",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "165",
      "name": "Manchado",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "166",
      "name": "Comentarios",
      "field": "area",
      "value": "",
    },
  ],
  [
    {
      "id": "171",
      "name": "Lente de Luz",
      "field": "picker",
      "value": "",
    },
    {
      "id": "172",
      "name": "Quebrado",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "173",
      "name": "Astillado",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "174",
      "name": "Rayado",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "175",
      "name": "Manchado",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "176",
      "name": "Comentarios",
      "field": "area",
      "value": "",
    },
  ],
  [
    {
      "id": "181",
      "name": "Fibras de guías de luz rotas",
      "field": "picker",
      "value": "",
    },
    {
      "id": "182",
      "name": "Porcentaje",
      "field": "number",
      "value": "",
    },
    {
      "id": "183",
      "name": "Comentarios",
      "field": "area",
      "value": "",
    },
  ],
  [
    {
      "id": "191",
      "name": "Cabezal Distal",
      "field": "picker",
      "value": "",
    },
    {
      "id": "192",
      "name": "Rayado",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "193",
      "name": "Abollado",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "194",
      "name": "Quebrado",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "195",
      "name": "Despegado",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "196",
      "name": "Comentarios",
      "field": "area",
      "value": "",
    },
  ],
  [
    {
      "id": "201",
      "name": "Goma de Angulación",
      "field": "picker",
      "value": "",
    },
    {
      "id": "202",
      "name": "Pegamento",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "203",
      "name": "Deteriorado",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "204",
      "name": "Separado",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "205",
      "name": "Pliegues hundidos",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "206",
      "name": "Tensión",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "207",
      "name": "Flojo",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "208",
      "name": "Rayado",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "209",
      "name": "Deteriorado",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "2010",
      "name": "Comentarios",
      "field": "area",
      "value": "",
    },
  ],
  [
    {
      "id": "211",
      "name": "Tubo de Insercion",
      "field": "picker",
      "value": "",
    },
    {
      "id": "212",
      "name": "Recubrimiento despegado",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "213",
      "name": "Pliegues",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "214",
      "name": "Flexibilidad",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "215",
      "name": "Comentarios",
      "field": "area",
      "value": "",
    },
  ],
  [
    {
      "id": "221",
      "name": "Pasaje de la pinza de biopsias",
      "field": "picker",
      "value": "",
    },
    {
      "id": "222",
      "name": "Restringido",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "223",
      "name": "No pasa",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "224",
      "name": "Comentarios",
      "field": "area",
      "value": "",
    },
  ],
  [
    {
      "id": "231",
      "name": "Pasaje del cepillo de limpieza",
      "field": "picker",
      "value": "",
    },
    {
      "id": "232",
      "name": "Restringido",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "233",
      "name": "No pasa",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "234",
      "name": "Comentarios",
      "field": "area",
      "value": "",
    },
  ],
  [
    {
      "id": "241",
      "name": "Apariencia de Equipo",
      "field": "picker",
      "value": "",
    },
    {
      "id": "242",
      "name": "Lugar del Defecto",
      "field": "text",
      "value": "",
    },
    {
      "id": "243",
      "name": "Comentarios",
      "field": "area",
      "value": "",
    },
  ],
  [
    {
      "id": "251",
      "name": "Tubo guía de luz cable OSF",
      "field": "picker",
      "value": "",
    },
    {
      "id": "252",
      "name": "Tubo guía de luz cable OSF",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "253",
      "name": "Plegado",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "254",
      "name": "Percudido",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "255",
      "name": "Pinchado",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "256",
      "name": "Cortado",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "257",
      "name": "Comentarios",
      "field": "area",
      "value": "",
    },
  ],
  [
    {
      "id": "261",
      "name": "Conector electrónico",
      "field": "picker",
      "value": "",
    },
    {
      "id": "262",
      "name": "Rajado",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "263",
      "name": "Corroido",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "264",
      "name": "Flojo",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "265",
      "name": "Comentarios",
      "field": "area",
      "value": "",
    },
  ],
  [
    {
      "id": "271",
      "name": "Contactos del conector EVIS",
      "field": "picker",
      "value": "",
    },
    {
      "id": "272",
      "name": "Hundidos",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "273",
      "name": "Corroido",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "274",
      "name": "Con fuga",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "275",
      "name": "Comentarios",
      "field": "area",
      "value": "",
    },
  ],
  [
    {
      "id": "281",
      "name": "Capuchon de la guía de luz",
      "field": "picker",
      "value": "",
    },
    {
      "id": "282",
      "name": "Flojo",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "283",
      "name": "Corroido",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "284",
      "name": "Comentarios",
      "field": "area",
      "value": "",
    },
  ],
  [
    {
      "id": "291",
      "name": "Extremo de angulacion",
      "field": "picker",
      "value": "",
    },
    {
      "id": "292",
      "name": "Serpentea",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "293",
      "name": "Rotado",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "294",
      "name": "Angula opuesto o chueco",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "295",
      "name": "Angulando se regresa la sección del Bending",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "296",
      "name": "Comentarios",
      "field": "area",
      "value": "",
    },
  ],
  [
    {
      "id": "301",
      "name": "Movimientos del control de angulación",
      "field": "picker",
      "value": "",
    },
    {
      "id": "302",
      "name": "Movimientos del control de angulación",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "303",
      "name": "Juego",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "304",
      "name": "Dirección del movimiento",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "305",
      "name": "Posición neutral Angulación",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "306",
      "name": "U",
      "field": "number",
      "value": "",
    },
    {
      "id": "307",
      "name": "D",
      "field": "number",
      "value": "",
    },
    {
      "id": "308",
      "name": "R",
      "field": "number",
      "value": "",
    },
    {
      "id": "309",
      "name": "L",
      "field": "number",
      "value": "",
    },
    {
      "id": "3010",
      "name": "Comentarios",
      "field": "area",
      "value": "",
    },
  ],
  [
    {
      "id": "311",
      "name": "Control de Angulación",
      "field": "picker",
      "value": "",
    },
    {
      "id": "312",
      "name": "Bloqueo certero",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "313",
      "name": "Posición",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "314",
      "name": "Rotación actual",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "315",
      "name": "Comentarios",
      "field": "area",
      "value": "",
    },
  ],
  [
    {
      "id": "321",
      "name": "Riendas de Angulación",
      "field": "picker",
      "value": "",
    },
    {
      "id": "322",
      "name": "Rotas",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "323",
      "name": "Desprendidas",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "324",
      "name": "Estiradas",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "325",
      "name": "Corridas",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "326",
      "name": "Comentarios",
      "field": "area",
      "value": "",
    },
  ],
  [
    {
      "id": "331",
      "name": "Bending Pasivo",
      "field": "picker",
      "value": "",
    },
    {
      "id": "332",
      "name": "Angulación",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "333",
      "name": "Aspecto",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "334",
      "name": "Parte al Connecting",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "335",
      "name": "Comentarios",
      "field": "area",
      "value": "",
    },
  ],
  [
    {
      "id": "341",
      "name": "Rigidez variable inoflex",
      "field": "picker",
      "value": "",
    },
    {
      "id": "342",
      "name": "Rango de variación",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "343",
      "name": "Rotación del anillo",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "344",
      "name": "Función certera",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "345",
      "name": "Comentarios",
      "field": "area",
      "value": "",
    },
  ],
  [
    {
      "id": "351",
      "name": "Rienda y Elevador de accesorio",
      "field": "picker",
      "value": "",
    },
    {
      "id": "352",
      "name": "Movimiento de la perilla",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "353",
      "name": "Angulo saliente Guidewire",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "354",
      "name": "Angulo de Fijación Guidewire",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "355",
      "name": "Angulo de elevación",
      "field": "boolean",
      "value": False,
    },
    {
      "id": "356",
      "name": "Comentarios",
      "field": "area",
      "value": "",
    },
  ],
];