# Generated by Django 5.1.5 on 2025-04-06 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AuthUser', '0001_initial'),
        ('Device', '0001_initial'),
        ('Entity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('client_sign', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PR', 'Programada'), ('CT', 'Completada'), ('AT', 'Atradasa')], max_length=50, verbose_name='Estado de orden')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entity.entity', verbose_name='Entidad')),
                ('client_AuthUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AuthUser.client', verbose_name='Cliente')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Entity.contract', verbose_name='Contrato')),
                ('device', models.ManyToManyField(blank=True, related_name='included_devices', to='Device.device', verbose_name='Equipos')),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AuthUser.engineer', verbose_name='Ingeniero')),
            ],
            options={
                'verbose_name': 'Orden de trabajo',
                'verbose_name_plural': 'Ordenes de trabajo',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SR', 'Sin revisar'), ('EPEN', 'Equipo pendiente'), ('OPSO', 'Equipo operativo sin observaciones'), ('OPCO', 'Equipo operativo con observaciones'), ('SSTT', 'Equipo se encuentra en servicio tecnico'), ('ERBJ', 'Equipo reportado de baja'), ('ENDB', 'Equipo no disponible')], default='Sin revisar', max_length=50, verbose_name='Estado final del equipo')),
                ('location', models.CharField(max_length=50, verbose_name='Ubicaion')),
                ('fields', models.JSONField(blank=True, default=dict, null=True)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Device.device', verbose_name='Equipo')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Order.order', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Protocolo',
                'verbose_name_plural': 'Protocolos',
            },
        ),
    ]
