# Generated by Django 5.1.5 on 2025-04-07 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_order_client_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='client_name',
            new_name='client_personal_name',
        ),
    ]
