# Generated by Django 5.1.5 on 2025-04-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_rename_client_name_order_client_personal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceprotocol',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ubicacion'),
        ),
    ]
