# Generated by Django 5.1.5 on 2025-04-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_alter_maintenanceprotocol_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceprotocol',
            name='status',
            field=models.CharField(choices=[('SR', 'Sin revisar'), ('EPEN', 'Equipo pendiente'), ('OPSO', 'Equipo operativo sin observaciones'), ('OPCO', 'Equipo operativo con observaciones'), ('SSTT', 'Equipo se encuentra en servicio tecnico'), ('ERBJ', 'Equipo reportado de baja'), ('ENDB', 'Equipo no disponible')], default='SR', max_length=50, verbose_name='Estado final del equipo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_personal_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
