name: Build and deploy Django app to Azure Web App - axion

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          python manage.py collectstatic --noinput

      - name: Remove venv and unnecessary files
        run: |
          find . -name '__pycache__' -type d -exec rm -rf {} +

      - name: Zip artifact
        run: zip -r release.zip . -x '*.git*'

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9FE7CCAE5FC74ED6A3D5E12E98E50EA5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7ABE3A92B32143BDBC2671BB92D46C16 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7F5C0EFB5132462F9CA5D89C0E0661F3 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'axion'
          slot-name: 'Production'
          package: release.zip
